version: "3.7"
services:
  node:
    container_name: nodeapp
    image: nodeapp
    build:
      args: build_date
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    networks:
      - nodeapp-networks
    volumes:
      - ./logs:/var/www/logs
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - nodeapp-networks
networks:
  nodeapp-network:
    driver: bridge
